FROM node:14-alpine AS build-generator
WORKDIR /src
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build


FROM nginx:alpine
COPY --from=build-generator /src/build /usr/share/nginx/html
CMD ["nginx-debug", "-g", "daemon off;"]