version: "3.9"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: frontend:0.2
    ports:
      - 8081:80
    depends_on:  
      - reverser
    networks:
      - two_tire_net

  reverser:
    image: backend:0.1
    ports:
      - 5000:5000
    environment:
      WELCOME: "<h1>This is from docker-compose</h1>"
      WELCOME_AGAIN: "This is a new welcome msg"
    volumes:
      - nginx-testvol:/test
    networks:
      - two_tire_net

volumes:
  nginx-testvol: 

networks:
  two_tire_net:
    driver: bridge
    
      